### ISSUE TITLE
Failed run-tempest action with logfile missing

### ISSUE THREAD

**Issue by jhobbs** [openstack-charmers/charm-tempest#2]
Running the tempest action for the first time gives me this:

`2016-05-11 16:11:03 INFO run-tempest Traceback (most recent call last):
2016-05-11 16:11:03 INFO run-tempest   File "/var/lib/juju/agents/unit-tempest-1/charm/actions/run-tempest", line 14, in <module>
2016-05-11 16:11:03 INFO run-tempest     charm.run_test('smoke')
2016-05-11 16:11:03 INFO run-tempest   File "lib/charm/openstack/tempest.py", line 320, in run_test
2016-05-11 16:11:03 INFO run-tempest     self.execute_tox(run_dir, logfile, tox_target)
2016-05-11 16:11:03 INFO run-tempest   File "lib/charm/openstack/tempest.py", line 297, in execute_tox
2016-05-11 16:11:03 INFO run-tempest     f = open(logfile, "w")
2016-05-11 16:11:03 INFO run-tempest FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/tempest//logs/run_20160511161032.log'
`

The problem is /var/lib/tempest//logs is missing.

More log: http://pastebin.ubuntu.com/16364954/

**Comment by jhobbs** [comment]
Fixed by 82c35c9.
